area/urls.py
from django.urls import path
from . import views


app_name = 'area'

urlpatterns = [
    path('', views.index, name='index'),
    path('/add', views.add, name='add'),
    path('/<int:id>/edit', views.edit, name='edit'),
    path('/<int:id>/delete', views.delete, name='delete'),
    path('/<int:id>/filial_data', views.filial_data, name='filial_data'),
    path('/<int:id>/grp_data', views.grp_data, name='grp_data'),
    path('/<int:id>/plot_data', views.plot_data, name='plot_data'),
    # path('/<int:id>/plot_data', views.plot_data, name='plot_data'),
]

site1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view.index, name='index'),
    path('area', include('area.urls')),
]

area/models.py
import json

import django.contrib.auth.forms
from django.conf import settings
from django.db import models
import datetime
# Create your models here.


class Filial(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(max_length=100)
    filial = models.ForeignKey(Filial, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class GrrProject(models.Model):
    name = models.CharField(max_length=30)
    filial = models.ForeignKey(Filial, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ProjType(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Phase(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Lic(models.Model):
    gos_num = models.CharField(max_length=20)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.gos_num


class Plot(models.Model):
    name = models.CharField(max_length=100)
    grp = models.ForeignKey(GrrProject, on_delete=models.CASCADE)
    phase = models.ForeignKey(Phase, on_delete=models.CASCADE)
    lic = models.ForeignKey(Lic, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class Month(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class MesureUnit(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class WorkType(models.Model):
    name = models.CharField(max_length=255)
    measure_unit = models.ForeignKey(MesureUnit, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} ({self.measure_unit})"

    class Meta:
        ordering = ['name']


class MainForm(models.Model):
    filial = models.ForeignKey(Filial, on_delete=models.RESTRICT, verbose_name="Филиал")
    company = models.ForeignKey(Company, on_delete=models.RESTRICT, verbose_name="Компания")
    grp = models.ForeignKey(GrrProject, on_delete=models.RESTRICT, verbose_name="ГР проект")
    proj_type = models.ForeignKey(ProjType, on_delete=models.RESTRICT, verbose_name="Тип проекта")
    plot = models.ForeignKey(Plot, on_delete=models.RESTRICT, verbose_name="Участок работ")
    phase = models.ForeignKey(Phase, on_delete=models.RESTRICT, verbose_name="Фаза работ на участке")
    lic = models.ForeignKey(Lic, on_delete=models.RESTRICT, null=True, blank=True, verbose_name="Лицензия")
    month = models.ForeignKey(Month, on_delete=models.RESTRICT, verbose_name="Месяц")
    work_type = models.ForeignKey(WorkType, on_delete=models.RESTRICT, verbose_name="Вид работ")
    measure_unit = models.ForeignKey(MesureUnit, on_delete=models.RESTRICT, verbose_name="Единица измерения")
    fact = models.BooleanField(verbose_name="Является ли параметр фактическим")
    value = models.FloatField(verbose_name="Значение")
    time_create = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    user_create = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, blank=True, null=True)
    # user_update = models.


class CompanyEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, Company):
            return o.__dict__
        return json.JSONEncoder.default(self, o)

area/forms.py
from django.forms.utils import ErrorList

from .models import MainForm
from django.forms import ModelForm

from area.models import *


class AreaForm(ModelForm):
    class Meta:
        model = MainForm
        exclude = ["measure_unit", "user_create"]

area/views.py
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from area.models import *
from .forms import AreaForm


# Create your views here.

def index(request):
    q = MainForm.objects
    order = request.GET["order"] if "order" in request.GET else "-id"
    # gos_num = request.GET["gos_num"] if "gos_num" in request.GET else "-id"

    area_list = q.order_by(order) if order else q.all()
    form = AreaForm

    return render(request, "area/index.html", {"area_list": area_list, "form": form})
    # return render(request, "area/index.html", {"form": form})


def edit(request, id):
    model = MainForm.objects.get(pk=id)
    if request.method == "POST":
        form = AreaForm(request.POST, instance=model)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/area")
    else:
        form = AreaForm(instance=model)

    return render(request, "area/edit.html", {"form": form})


def delete(request, id):
    MainForm.objects.get(pk=id).delete()
    return HttpResponseRedirect("/area")


def filial_data(request, id):
    company_list = Company.objects.filter(filial_id=id)
    grp_list = GrrProject.objects.filter(filial_id=id)
    ret = {'company': {}, 'grp': {}}
    for c in company_list:
        ret['company'][c.id] = c.name
    for c in grp_list:
        ret['grp'][c.id] = c.name
    return JsonResponse(ret)


def grp_data(request, id):
    plot_list = Plot.objects.filter(grp_id=id)
    ret = {}
    for c in plot_list:
        ret[c.id] = c.name
    return JsonResponse(ret)


def plot_data(request, id):
    plot = Plot.objects.get(pk=id)
    if not plot.lic_id:
        return JsonResponse({})
    one_lic = Lic.objects.get(id=plot.lic_id)
    if not one_lic:
        return JsonResponse({})
    ret = {"id": one_lic.id, "name": one_lic.name, "gos_num": one_lic.gos_num}
    return JsonResponse(ret)


def add(request):
    if request.method == "POST":
        form = AreaForm(json.loads(request.body.decode('utf-8')))

        if form.is_valid():
            work_type = WorkType.objects.get(pk=form.cleaned_data['work_type'].id)
            o = form.save(commit=False)
            o.measure_unit_id = work_type.measure_unit_id
            o.user_create = request.user.id if request.user.is_authenticated else None
            o.time_create = datetime.datetime.now()
            o.save()

            # order = request.GET["order"] if "order" in request.GET else ""
            # gos_num = request.GET["gos_num"] if "gos_num" in request.GET else ""

            q = MainForm.objects
            area_list = q.order_by('-id').all()

            return render(request, "area/area_list.html", {"area_list": area_list})
        else:
            return HttpResponse("Data is invalid: " + str(form.errors))

    return HttpResponse("Must be POST method")



area/templates/area/add.html
{% extends "layout.html" %}

{% block title %}
Добавить площадь
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
{{form.as_p}}
<button type="submit">Добавить</button>
</form>
{% endblock %}

area/templates/area/area_list.html
<table class="table table-bordered table-striped">
    <tr>
        <th><a href="?order=filial "> Филиал </a></th>
        <th><a href="?order=company"> Предприятие </a></th>
        <th><a href="?order=grp"> Проект ГРР </a></th>
        <th><a href="?order=proj_type"> Тип проекта </a></th>
        <th><a href="?order=plot"> Участок работ </a></th>
        <th><a href="?order=phase"> Фаза работ </a></th>
        <th><a href="?order=lic"> Лицензия </a></th>
        <th><a href="?order=month"> Месяц </a></th>
        <th><a href="?order=work_type"> Вид работ </a></th>
        <th><a href="?order=measure_unit"> Единица измерения </a></th>
        <th><a href="?order=fact"> Фактические данные </a></th>
        <th><a href="?order=value"> Значение </a></th>
    </tr>
    {% for a in area_list %}
    <tr>
        <td>{{a.filial}}</td>
        <td>{{a.company}}</td>
        <td>{{a.grp}}</td>
        <td>{{a.proj_type}}</td>
        <td>{{a.plot}}</td>
        <td>{{a.phase}}</td>
        <td>{{a.lic}}</td>
        <td>{{a.month}}</td>
        <td>{{a.work_type.name}}</td>
        <td>{{a.measure_unit}}</td>
        <td>{{a.fact}}</td>
        <td>{{a.value}}</td>
        <td>
            <a href="{% url 'area:edit' a.pk%}">Редактировать</a>
            <a href="{% url 'area:delete' a.pk%}">Удалить</a>
        </td>
    </tr>
    {% endfor %}
</table>

area/templates/area/edit.html
{% extends "layout.html" %}

{% block title %}
Изменить
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
{{form.as_p}}
<button type="submit">Изменить</button>
</form>
{% endblock %}

area/templates/area/index.html
{% extends "layout.html" %}

{% block title %}
Площади - title
{% endblock %}

{% load static %}
{% block js %}
<script src="https://unpkg.com/axios@1.3.6/dist/axios.min.js"></script>
<script src="{% static 'mainform.js' %}?v=6"></script>
<script src="{% static 'index.js' %}"></script>
{% endblock %}

{% block content %}
<h1>   Ввод данных по месяцам работы</h1>
<hr>
<form action="" method="post" id="area-form">
    {% csrf_token %}
<!--{{form.as_p}}-->
<table class="table" style="width: auto">
    {% for f in form %}
    <tr>
        <td style="padding: 5px">{{f.label}}</td>
        <td style="padding: 5px">{{f}}{{f.help_text}}{{f.errors}}</td>
    </tr>
    {% endfor %}
</table>

<button type="submit">Добавить</button>
    <hr>
</form>
<div id="area-list">
    {% include 'area_list.html' %}
</div>
{% endblock %}

site1/templates/site1/index.html
{% extends "layout.html" %}

{% block title %}
Главная страница - title
{% endblock %}

{% block content %}
Главная страница - body
<br>
Пользователь: {{ uname }}
{% endblock %}

site1/templates/site1/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мой сайт - {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Таблица ПО1</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/area">Передать значения</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div>{% block content %}{% endblock %}</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  {% block js %}{% endblock %}
  </body>
</html>